% Radar Waveform Analyzer Report
%
% Generated by MATLAB 9.8 and Phased Array System Toolbox 4.3
%
% Generated on 17-Sep-2020 21:55:22
%
% Waveform ...................................... Rectangular
%
% Sample Rate (Hz) .............................. 1e+11
% PRF (Hz) ...................................... 100000
% Number of Pulses .............................. 1
% Pulse Width (s) ............................... 1e-07
% Propagation Speed (m/s) ....................... 3e+08
%
% Range Resolution (m) .......................... 15
% Doppler Resolution (Hz) ....................... 100000
% Minimum Unambiguous Range (m) ................. 15
% Maximum Unambiguous Range (m) ................. 1500
% Maximum Doppler (Hz) .......................... 50000
% Time Bandwidth Product ........................ 1T
% Duty Cycle (%) ................................ 1
